"""second migration

Revision ID: 9fdcc479ee7d
Revises: 39688f001e69
Create Date: 2021-07-27 18:14:08.704242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdcc479ee7d'
down_revision = '39688f001e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('divvy', sa.Column('to_station_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('divvy', 'to_station_name')
    # ### end Alembic commands ###
